// Package openapigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapigen

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for PaymentStatus.
const (
	PaymentStatusCompleted  PaymentStatus = "completed"
	PaymentStatusFailed     PaymentStatus = "failed"
	PaymentStatusProcessing PaymentStatus = "processing"
)

// Defines values for ReviewDecision.
const (
	Approve ReviewDecision = "approve"
	Reject  ReviewDecision = "reject"
)

// Defines values for UserRole.
const (
	Cs        UserRole = "cs"
	Operation UserRole = "operation"
)

// Defines values for StatusFilter.
const (
	StatusFilterCompleted  StatusFilter = "completed"
	StatusFilterFailed     StatusFilter = "failed"
	StatusFilterProcessing StatusFilter = "processing"
)

// Defines values for ListPaymentsParamsStatus.
const (
	Completed  ListPaymentsParamsStatus = "completed"
	Failed     ListPaymentsParamsStatus = "failed"
	Processing ListPaymentsParamsStatus = "processing"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code HTTP-aligned numeric error code.
	Code int `json:"code"`

	// Details Optional structured details (validation errors, etc.).
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	// Token JWT bearer token. Send as `Authorization: Bearer TOKEN`.
	Token string `json:"token"`
	User  User   `json:"user"`
}

// Payment defines model for Payment.
type Payment struct {
	// Amount Amount in minor currency units (e.g. IDR sen).
	Amount     int64      `json:"amount"`
	CreatedAt  time.Time  `json:"created_at"`
	Currency   string     `json:"currency"`
	Id         string     `json:"id"`
	Merchant   string     `json:"merchant"`
	ReviewedAt *time.Time `json:"reviewed_at"`

	// ReviewedBy Email of the operation user who last reviewed this payment.
	ReviewedBy *string       `json:"reviewed_by"`
	Status     PaymentStatus `json:"status"`
}

// PaymentList defines model for PaymentList.
type PaymentList struct {
	Data []Payment `json:"data"`

	// Total Total matching rows (across all pages).
	Total int `json:"total"`
}

// PaymentStatus defines model for PaymentStatus.
type PaymentStatus string

// PaymentSummary defines model for PaymentSummary.
type PaymentSummary struct {
	Completed  int `json:"completed"`
	Failed     int `json:"failed"`
	Processing int `json:"processing"`
	Total      int `json:"total"`
}

// ReviewDecision defines model for ReviewDecision.
type ReviewDecision string

// ReviewRequest defines model for ReviewRequest.
type ReviewRequest struct {
	Decision ReviewDecision `json:"decision"`

	// Note Optional note recorded with the review.
	Note *string `json:"note,omitempty"`
}

// User defines model for User.
type User struct {
	Email openapi_types.Email `json:"email"`
	Role  UserRole            `json:"role"`
}

// UserRole defines model for User.Role.
type UserRole string

// IdSearch defines model for IdSearch.
type IdSearch = string

// Limit defines model for Limit.
type Limit = int

// Offset defines model for Offset.
type Offset = int

// PaymentId defines model for PaymentId.
type PaymentId = string

// SortParam defines model for SortParam.
type SortParam = string

// StatusFilter defines model for StatusFilter.
type StatusFilter string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// ListPaymentsParams defines parameters for ListPayments.
type ListPaymentsParams struct {
	// Status Filter by payment status.
	Status *ListPaymentsParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// Id Filter by exact payment ID.
	Id *IdSearch `form:"id,omitempty" json:"id,omitempty"`

	// Sort Sort field. Prefix `-` for desc.
	// Allowed: `created_at`, `-created_at`, `amount`, `-amount`.
	Sort *SortParam `form:"sort,omitempty" json:"sort,omitempty"`

	// Limit Page size (1..100).
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Page offset (>=0).
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListPaymentsParamsStatus defines parameters for ListPayments.
type ListPaymentsParamsStatus string

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = LoginRequest

// ReviewPaymentJSONRequestBody defines body for ReviewPayment for application/json ContentType.
type ReviewPaymentJSONRequestBody = ReviewRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login with email + password
	// (POST /dashboard/v1/auth/login)
	LoginUser(w http.ResponseWriter, r *http.Request)
	// List payments
	// (GET /dashboard/v1/payments)
	ListPayments(w http.ResponseWriter, r *http.Request, params ListPaymentsParams)
	// Payment summary (totals by status)
	// (GET /dashboard/v1/payments/summary)
	GetPaymentSummary(w http.ResponseWriter, r *http.Request)
	// Review a payment (approve/reject)
	// (PUT /dashboard/v1/payments/{id}/review)
	ReviewPayment(w http.ResponseWriter, r *http.Request, id PaymentId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Login with email + password
// (POST /dashboard/v1/auth/login)
func (_ Unimplemented) LoginUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List payments
// (GET /dashboard/v1/payments)
func (_ Unimplemented) ListPayments(w http.ResponseWriter, r *http.Request, params ListPaymentsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Payment summary (totals by status)
// (GET /dashboard/v1/payments/summary)
func (_ Unimplemented) GetPaymentSummary(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Review a payment (approve/reject)
// (PUT /dashboard/v1/payments/{id}/review)
func (_ Unimplemented) ReviewPayment(w http.ResponseWriter, r *http.Request, id PaymentId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// LoginUser operation middleware
func (siw *ServerInterfaceWrapper) LoginUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPayments operation middleware
func (siw *ServerInterfaceWrapper) ListPayments(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPaymentsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "id" -------------

	err = runtime.BindQueryParameter("form", true, false, "id", r.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", r.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPayments(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPaymentSummary operation middleware
func (siw *ServerInterfaceWrapper) GetPaymentSummary(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPaymentSummary(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReviewPayment operation middleware
func (siw *ServerInterfaceWrapper) ReviewPayment(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id PaymentId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReviewPayment(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/dashboard/v1/auth/login", wrapper.LoginUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dashboard/v1/payments", wrapper.ListPayments)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dashboard/v1/payments/summary", wrapper.GetPaymentSummary)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/dashboard/v1/payments/{id}/review", wrapper.ReviewPayment)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RZXXPbutH+Kzt83wu7pSg6tjOJZjpTp0lan6YnGluZcxF5SohYSTgmAQYAbet49N87",
	"C/DTomynk+O2vrJIYPfBfj4L3gepygslUVoTTO6DgmmWo0Xtfp3zS2Q6XdP/HE2qRWGFksEk+CgyixoW",
	"G8A7lloo2CZHaeH8fRSEgaAl30rUmyAMJMsxmASCB2Fg0jXmjMTZTUFPjdVCroLtNgw+iVzYXU1TtkIw",
	"4jeEg6MoOorjw30aMiegq4TjkpWZDSZHcRwGObsTeZnXv4SsfoU1GCEtrlA7NJ+XS4P74Cj3Eg7mZRwf",
	"45/2Q/ILhzF1McSDGKbeqOd8CEZtbzgoS8FbBAWz6wdW1/itFBp5MLG6xC4YvGN5kdHCN8sjfrp4lY5e",
	"LV/j6IQfL0ZvWcxGR4vXy2P2Nk6P8FUQDrjtUmk7pajZBUmvYCkw4xFMNS7FHSSjBJZKAy2M5vIsy9Qt",
	"8gkkqUZmkf+T2SSEZNT/yXJVSv+i+jeayz0mN0r3Dd6esSN1+CiW2dL40H4s5OtgN279Pt/7t30okpz9",
	"1eVchhbJOYVWKRpDGMJgyUSGPLjaRbclN5pCSYMuNd8xfoHfSjQuRlMlLUr3LyuKTKSMQI9/NYT8voPg",
	"/zUug0nwf+M27cf+rRl/0Frpi0qJV9m3QKWQzp8pxkFpcGeGtmqAPwHcsExwByIKtmHwFyWXmUhfFKtR",
	"pU4RhAGpLAgJzDkMwa6ZBUaRZ8CuhQFVoG6xflR6IThH+XJgz0q7RmlJOnJYlBa0yhC4Qg9+zW4QWEpx",
	"4iCeS4tasswJfjmYXyTeFZgSRoP6BjUgbXGQflb2oyol/w94mCy0JN0OyBfJSrtWWvyGLwjmH8KlMKWE",
	"kC74YYFMowarrpECa1sXApe+fYHUeDVFoRU+u1PFcbcC/W02m45YJlYSOcgyRy1S7wKgDVSImmJ3Eg/0",
	"NUJtmcicDsa5IMEsm3Z0+w7R1/u58OvAWF2mttTIoRIEB22meygmBLRp5BpSpV8tfsXUkvocjWEr7Jfl",
	"suOxCeS7lnQmHKzYbWf76m3WqrgaUP9JrYTslM2+0TFnIutDayrDny0aG6UqpyKtdM5sMKk27OAKg4IZ",
	"c6s07wtrnnZEdJ7lQn5CubLrLiXZc9Zac7P9kdPuizFv1Z0g++mXWT904RIlB2YgOavc5CwygXd+1ezz",
	"3z/8nERDdiiNb6SPpdYXU7Gd7vlqjzsBQ2er+M/uqTw/2D3WmXtObSAXkhKm1BpluoFSCmvgAKNVBOfv",
	"L8CgPOxl0tFpTH8dpwlpX58EQ+nVIRiT+3YDZxZHVuQ4ZKQaST9Yzt9fDC0W/EfQNsoSna6ZN1Qrbaau",
	"VYFcsKEtGm8E3j5+OFlmGVuQLF9H9gtZbHZ99IGiGtQS7BrbpgwUBHC7VpAxY6GW4Ft3RcWi5+iuCNkT",
	"8VhFlueCO4Hp+HRjvLAOt44Xw5b4daLhkRj+JIaKEWfWdSVhMX8uZhJaaWFas437rSzLdk09o8eQM5uu",
	"qdhq4kIHLNXKGKJGULAVmn4enA4PKV3rONC1zkeOfNl44t9nxK2wMs+Z3gw10VpmN8hP4qHErdR0F54O",
	"retge3JtY/rvMaHfFH6HQVrrXrjUeI+pMMKzm9q8rCi0ukE3C7rVQ/b02/e2R96R+1gwPkCxDQOp7ACb",
	"aVgFvQaNqdIcOdwKu3YFwCc6hWDO7urOeBrHT/XGBueQib5UHWlP53+6tRMx7wUuJXpTq4Ymt+HO7eTs",
	"IqQyhWmphd1ckj09Pt+Pqf22vz7WUH/6ZVYPmSTJv22hr60tPGMVcql23VDPEsCZWS8U0xzOpuduSM+V",
	"FFbRMYBJXjmEfgmZqpz+qcqvieZyLme3ys0tZjKXI0hSk0xAI+MjJbNNNb6AVc0mJ9T47I3clsaOyQQM",
	"y9GxjtQkUGSlcUHBFiITdkNiqpge+4hupM4lVBOeRjBWZBk1/aTNocSPgQ7yWZZBMm5OPv5DAih5oYR0",
	"nOAuxcJCRjzqECovAquJDzElYUyJfC4XG0imny9n0BF2czQmYjt2+6sbCyus67T1/c37rtGDMLhB7XMs",
	"OIriKKaIUwVKVohgEhxHcXTsWJ9du7jYp8xFuDIDNOgCbamlAebQkwOcVXvzJ/XbCKblIqPxojJH1A3z",
	"cx5MPL10+eQjHI19p/jmh81cPbK+7ecRdfiHNyKv4vhH694/77kFYEoX1Msyc6PniUcwJLhBOu5c3Lgt",
	"R09v6Y202zA4fY6e/h1Bt7AEk69XYWDqtlmdxdVdV53gj9AZSyxbGSpcrvpckZx+1NV5R4hW+EjIFWwl",
	"pAuwpmrAZVkUSlsDy+ZyLfH0KQn9zfLIcZS5NO4i2i0QPAl97VDauied20KaG5PeJeGDqBXGTmvIYe++",
	"++uwSdsl494F4TZ8cn1zf/6Mte096jMW+7vyZyysrrG3V79jsnR57FCqCGOJ1Dde/99KlX73/Xq17eeO",
	"MG3r6WRLE2KPZMzYtMx1MHPOViuNK5cyKQW0gULdouvHVLXbhl0JglvBVzhQqv+K9gFZ/v3DodY0dN35",
	"8FzRf61/6z5dW/jA8XNDVcfXqcPvdfq94Nuxp1KuTZcDjp9pJo27nKNOXX9uWGqV94mMVYDCrlFD0swL",
	"yVweKFmzo0NXD/3MkAC98HTpMIIL302Nv2vucK9oLi8aqteqd6TK3aZDpuQK9Q6v0lWlP4nfDpVeL7Se",
	"Vb+39rYfw3wx+/GEoz//vDDjaEb4oYtuwgVONnJynDcz1YCy4N2W+qK19SQ+fnpT+zXF7Th5ekfzJcFt",
	"ePv0hubj0gvUg9oXTVYc9MeQfeXA6dA3daw/JJMpy2DB0muUHA5ydo2gSwlj4Cq9Rg3uFAZJeKmzaqib",
	"jMcZbVwrYydv4jexS4xK+f3+L0z0oPlI6U5JPGL48/LgBNjubk64vdr+KwAA//+ex4Z+SiAAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
